### Register User
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "<someEmail@gmail.com>",
    "password": "<supersecurepassword>"
}

### Resend Verification Email
POST http://localhost:3000/api/resend-verification
Content-Type: application/json

{
    "email": "<someEmail@gmail.com>",
}

### Log In and Capture Token
# @name loginUser
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "<someEmail@gmail.com>",
    "password": "<supersecurepassword>"
}

### This separator is important. The variable is defined after loginUser response.
@jwtToken = {{loginUser.response.body.token}}


### Link Minecraft Username
POST http://localhost:3000/api/mc-username
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "mc_username": "<MinecraftUsername>"
}

### Verify Minecraft Username with code
### Retreive UUID of Minecraft username from https://api.minecraftservices.com/minecraft/profile/lookup/name/<username>
POST http://localhost:3000/api/internal/mc-verify
Content-Type: application/json
X-Internal-API-Key: <SOME_LONG_SECURE_INTERNAL_API_KEY>

{
    "code": "<MINECRAFT_VERIFICATION_CODE_GENERATED>",
    "mc_uuid": "<MINECRAFT_UUID>"
}