// Constants
const ACCOUNT_LINK_LIMIT = 3;
const EMAIL_VERIFICATION_EXPIRATION_MINUTES = 15;
const MC_CODE_EXPIRATION_MINUTES = 15;
const SEVEN_DAYS_IN_MS = 7 * 24 * 60 * 60 * 1000;
const ACCESS_TOKEN_EXPIRES_IN = '15m';
const REFRESH_TOKEN_EXPIRES_IN = '7d';
const MC_SERVICES_API_URL = 'https://api.minecraftservices.com/minecraft/profile/lookup/name'
const PG_ERROR_CODES = {
    UNIQUE_VIOLATION: '23505'
};

module.exports = {
    ACCOUNT_LINK_LIMIT,
    EMAIL_VERIFICATION_EXPIRATION_MINUTES,
    MC_CODE_EXPIRATION_MINUTES,
    SEVEN_DAYS_IN_MS,
    ACCESS_TOKEN_EXPIRES_IN,
    REFRESH_TOKEN_EXPIRES_IN,
    MC_SERVICES_API_URL,
    PG_ERROR_CODES
};
